# This Makefile generates the Components Needed for HW4
# for MSSE Chem 279 - Fall Semester
# University of California, Berkeley
# 
# Creator:  Anna Weber
# Date Created: Nov 2, 2022

# This is the main build makefile

MOL_DIR = src/molecules
FUNC_DIR = src/functions
EXCEPTIONS = src/exceptions
MAIN_DIR = src/main
UTIL_DIR = src/util

all:	


debug:


run:
	cd $(MAIN_DIR); make run

cleanall:
